select
    id,
    name,
    description,
    avatar_file_name,
    avatar_content_type,
    avatar_file_size,
    avatar_updated_at,
    user_id,
    published,
    created_at,
    updated_at,
    initials,
    destroy_soon
from
    environments;
